kind: Pod
apiVersion: v1
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
#      env:
#        - name: PGUSER
#          valueFrom:
#            secretKeyRef:
#              name: secret-store
#              key: pguser
#        - name: PGPASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: secret-store
#              key: pgpassword
  volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: {{ .Values.secretProviderClassName }}