apiVersion: secrets-store.csi.x-k8s.io/v1
kind:       SecretProviderClass

metadata:
  name: {{ .Values.secretProviderClassName }}

spec:
  provider: azure

  parameters:
    usePodIdentity:         "false"
    useVMManagedIdentity:   "true"
    userAssignedIdentity: {{ .Values.umi }}
    tenantId:               {{ .Values.tenantId          }}
    subscriptionId:         {{ .Values.subscriptionId    }}
    resourceGroup:          {{ .Values.resourceGroupName }}
    keyvaultName:           {{ .Values.keyVaultName      }}

    objects: |
      array:
      {{- range .Values.secrets }}
        - |
          objectName:    {{ . }}
          objectType:    secret
          objectVersion: ""
      {{- end }}

