kind: Pod
apiVersion: v1
metadata:
  name: postgres-cli
spec:
  containers:
    - name:  postgres-cli
      image: acrleif01.azurecr.io/postgres:latest
      volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly:  true
        - name: varlog
          mountPath: "/var/log"
      env:
        - name:  PGPASSWORD
          value: {{ .Values.pgpassword }}
        - name:  PGUSER
          value: {{ .Values.pguser }}
        - name:  PGHOST
          value: {{ .Values.pghost }}
        - name:  PGPORT
          value: "{{ default 5432 .Values.port }}"

    - name: consumer
      image: busybox:1.28
      args: [ /bin/sh, -c, 'tail -n+1 -F /var/log/1.log' ]
      volumeMounts:
        - name: varlog
          mountPath: /var/log
  volumes:
    - name: secrets-store01-inline
      csi:
        driver:   secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: {{ .Values.secretProviderClassName }}
    - name: varlog
      emptyDir: {}