parameters:
  - name: tf_creds

stages:
  - stage: terraform_plan
    displayName: Terraform Plan
    jobs:
      - job: terraform_plan
        displayName: Terraform Plan
        workspace:
          clean: all
        steps:
          - task: DownloadSecureFile@1
            name: tf_creds
            inputs:
              secureFile: ${{ parameters.tf_creds }}
          - bash: |
              echo $(tf_creds.secureFilePath)

          - task: CopyFiles@2
            inputs:
              sourceFolder: $(tf_creds.secureFilePath)
              contents: "credentials.tfrc.json"
              targetFolder: "~/.terraform.d"

          - bash: |
              ls -al ~
              ls -al ~/.terraform.d
