parameters:
  - name: direction
    default: up
    displayName: Migration Direction
    values:
      - up
      - down

variables:
  - group: infra
  - group: devops-dev
  - group: pg-dev

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - master
      - main
  paths:
    include:
      - pipelines/db_migrate_dev.yml
      - node/**/*
      - migrations/**/*
      - scripts/migrate_sql.sh

resources:
  pipelines:
    - pipeline: infra
      source: leriksen.terraform
      trigger:
        branches:
          - master
          - main

stages:
  - stage: db_migrate
    displayName: Migrate DB
    jobs:
      - deployment: db_migrate
        displayName: Migrate DB
        workspace:
          clean: all
        environment: $(environment)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: UseNode@1
                  inputs:
                    version: $(node_version)
                    checkLatest: true

                - task: Bash@3
                  displayName: Install DB Migrate
                  inputs:
                    targetType: inline
                    script: |
                      npm install -g db-migrate
                      npm install -g db-migrate-pg

                - task: Bash@3
                  displayName: Migrate DB
                  env:
                    PGUSER:              $(pguser)
                    PGPASSWORD:          $(pgpassword)
                    PGHOST:              $(pghost)
                    PGDATABASE:          $(pgdatabase)
                    PGPORT:              5432
                    DRY_RUN:             $(dry_run)
                    MIGRATE_DIRECTION:   $(migrate_direction)
                    INIT_MIGRATE:        $(initial_migration)
                    PERSONIFY_READ_USER: env_password
                  inputs:
                    targetType: filePath
                    workingDirectory: scripts
                    filePath: scripts/migrate_sql.sh
                    arguments: >
                      ../migrations