variables:
  - group: devops-dev
  - group: pg-dev

pool:
  vmImage: ubuntu-22.04

trigger: none

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build job
        steps:
          - bash: |
              ls -al

          - task: Docker@2
            displayName: Build and push an image to container registry
            workingDirectory: $(Build.SourcesDirectory)
            inputs:
              command: buildAndPush
              repository: postgres
              dockerfile: $(Build.SourcesDirectory)/docker/Dockerfile
              containerRegistry: tf_sc_acr
              tags: |
                0.0.1-$(Build.BuildId)
                latest