variables:
  - group: devops-dev
  - group: pg-dev

pool:
  vmImage: ubuntu-22.04

trigger:
  batch: true
  branches:
    include:
      - master
      - main

stages:
  - template: ./templates/plan.yml
    parameters:
      tf_creds: credentials.tfrc.json
      tf_workspace: pg

  - template: ./templates/apply.yml
    parameters:
      tf_creds: credentials.tfrc.json
      tf_workspace: pg
      environment: $(environment)
