variables:
  - group: terraform-base
  - group: devops-base
  - group: devops-non-prod
  - group: devops-dev

pool:
  vmImage: ubuntu-22.04

trigger:
  batch: true
  branches:
    include:
      - master
      - main

stages:
  - template: ./templates/plan.yml
    parameters:
      environment:        $(environment)
      project:            $(project)
      subscription_id:    $(subscription_id)
      tf_creds:           'credentials.tfrc.json'

  - template: ./templates/apply.yml
    parameters:
      environment:        $(environment)
      project:            $(project)
      subscription_id:    $(subscription_id)
      tf_creds:           'credentials.tfrc.json'