variables:
  - group: devops-dev
  - group: pg-dev
  - group: infra

pool:
  vmImage: ubuntu-22.04

trigger:
  batch: true
  branches:
    include:
      - master
      - main
  paths:
    include:
      - pipelines/secrets_helm_deploy.yml
      - helm/secrets/**/*

stages:
  - stage: secretproviderclass
    displayName: Config Secret Provider Class
    jobs:
      - deployment: secretproviderclass
        displayName: Config Secret Provider Class
        workspace:
          clean: all
        environment: $(environment)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: KubectlInstaller@0

                - task: HelmInstaller@1

                - task: AzureCLI@2
                  displayName: Kubectl Config
                  inputs:
                    azureSubscription: sc-azure-pg
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az aks get-credentials -n pg -g pg
                    addSpnToEnvironment: true

                - task: Bash@3
                  displayName: Install CSI Driver
                  inputs:
                    targetType: inline
                    script: |
                      echo "Adding Helm repo for Secret Store CSI..."
                      helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
                      
                      echo "Installing Secrets Store CSI Driver using Helm..."
                      out=$(helm upgrade --install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --create-namespace --namespace csi-driver)
                      rc=$?
                      
                      kubectl get pods --namespace=csi-driver
                      
                      exit $rc

                - task: Bash@3
                  displayName: Install Azure KV CSI Provider
                  inputs:
                    targetType: inline
                    script: |  
                      echo "Installing Secrets Store Provider for Azure Key Vault..."

                      kubectl apply -f https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/deployment/provider-azure-installer.yaml --namespace csi-driver
                      kubectl get pods -n csi-driver

                - task: HelmDeploy@0
                  displayName: Helm Package
                  inputs:
                    command: package
                    chartPath: helm/secrets
                    chartVersion: 0.1.0
                    destination: $(Build.ArtifactStagingDirectory)
                    arguments: --app-version $(Build.BuildNumber)
                    save: false

                - task: PublishPipelineArtifact@1
                  displayName: Save heml package
                  inputs:
                    targetPath: $(Build.ArtifactStagingDirectory)/secrets-0.1.0.tgz
                    artifact: helm_secretproviderclass_package
                    publishLocation: pipeline

                - task: HelmDeploy@0
                  displayName: Helm Deploy
                  inputs:
                    namespace:                   $(environment)
                    connectionType:              Kubernetes Service Connection
                    kubernetesServiceConnection: tf_sc_aks
                    command:                     upgrade
                    chartType:                   FilePath
                    chartPath:                   $(Build.ArtifactStagingDirectory)/secrets-0.1.0.tgz
                    chartVersion:                0.1.0
                    releaseName:                 secrets
                    valueFile:                   helm/secrets/values.yaml
                    arguments:                   --install --create-namespace --timeout 30s
