pool:
  vmImage: ubuntu-22.04

trigger:
  batch: true
  branches:
    include:
      - master
      - main
  paths:
    include:
      - scripts/run_sql.sh
      - sql/**/*

stages:
  - stage: Test
    displayName: Test scripts and sql
    jobs:
      - job: Test
        displayName: Test
        steps:
          - task: Bash@3
            displayName: Test scripts and sql
            inputs:
              targetType: inline
              workingDirectory: $(System.DefaultWorkingDirectory)
              script: |
                set -euo pipefail
                                
                output=$(scripts/run_sql.sh sql/manifest.txt fixtures/secrets.json > test.out)
                rc=$?
                
                if [[ "${rc}" -ne 0 ]]; then
                  echo "failed"                  
                else
                  echo "succeeded"
                fi
                
                echo "_____________"
                echo "script output"
                echo "-------------"
                cat test.out
                
                exit $rc
