kind: Pod
apiVersion: v1
metadata:
  name: postgres-cli
spec:
  containers:
    - name: postgres-cli
      image: acrleif01.azurecr.io/postgres:latest
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      env:
        - name: PGPASSWORD
          value: $(pgpassword)
        - name: PGUSER
          value: $(pguser)
        - name: PGHOST
          value: $(pghost)
        - name: PGPORT
          value: 5432
        - name: PGDATABASE
          value: $(pgdatabase
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: {{ .Values.secretProviderClassName }}
